# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170213_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='involve',
            name='job',
        ),
        migrations.RemoveField(
            model_name='involve',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='job',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Involve',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
