# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170213_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='abstract',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
