# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_job_abstract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='abstract',
            new_name='title',
        ),
    ]
